Parameters:
  KakfaClusterName:
    Type: String
    Description: Application Name
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids
  VolumeSize:
    Type: Number
    Description: Kafka Nodes EBS Volume Size
  KMSKafkaArn:
    Type: String
    Description: KMS Kafka Arn
  NumberOfBrokerNodes:
    Type: Number
    Description: Number Of Broker Nodes
  BastionHostSubnetId:
    Type: String
    Description: Bastion Host Subnet Id
  BastionHostKeyName:
    Type: String
    Description: Bastion Host Key Name

Resources:
  KafkaCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      ClusterName: !Ref KakfaClusterName
      KafkaVersion: 2.6.1
      NumberOfBrokerNodes: !Ref NumberOfBrokerNodes
      EnhancedMonitoring: PER_BROKER
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: !Ref KMSKafkaArn
        EncryptionInTransit:
          ClientBroker: TLS_PLAINTEXT
          InCluster: true
#      OpenMonitoring:
#        Prometheus:
#          JmxExporter:
#            EnabledInBroker: "true"
#          NodeExporter:
#            EnabledInBroker: "true"
#      ConfigurationInfo:
#        Arn: ReplaceWithConfigurationArn
#        Revision: 1
#      ClientAuthentication:
#        Tls:
#          CertificateAuthorityArnList:
#            - ReplaceWithCAArn
      Tags:
        Environment: Test
        Owner: QATeam
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        InstanceType: kafka.t3.small
#        SecurityGroups:
#          - ReplaceWithSecurityGroupId
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: !Ref VolumeSize
        ClientSubnets: !Ref Subnets
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Example security group
      VpcId: !ImportValue 'eksctl-toto-cluster::VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d3f551818b21ed81
      InstanceType: t2.micro
      SubnetId: !Ref BastionHostSubnetId
      KeyName: !Ref BastionHostKeyName
      SecurityGroupIds:
        - !GetAtt
          - BastionHostSecurityGroup
          - GroupId
Outputs:
  BastionHostSecurityGroupId:
    Value: !GetAtt
      - BastionHostSecurityGroup
      - GroupId
  BastionHostPublicDnsName:
    Value: !GetAtt
      - BastionHost
      - PublicDnsName