Parameters:
  KakfaClusterName:
    Type: String
    Description: Application Name
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids
  VolumeSize:
    Type: Number
    Description: Kafka Nodes EBS Volume Size
  KMSKafkaArn:
    Type: String
    Description: KMS Kafka Arn
  NumberOfBrokerNodes:
    Type: Number
    Description: Number Of Broker Nodes

Resources:
  KafkaCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      ClusterName: !Ref KakfaClusterName
      KafkaVersion: 2.6.1
      NumberOfBrokerNodes: !Ref NumberOfBrokerNodes
      EnhancedMonitoring: PER_BROKER
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: !Ref KMSKafkaArn
        EncryptionInTransit:
          ClientBroker: TLS_PLAINTEXT
          InCluster: true
#      OpenMonitoring:
#        Prometheus:
#          JmxExporter:
#            EnabledInBroker: "true"
#          NodeExporter:
#            EnabledInBroker: "true"
#      ConfigurationInfo:
#        Arn: ReplaceWithConfigurationArn
#        Revision: 1
#      ClientAuthentication:
#        Tls:
#          CertificateAuthorityArnList:
#            - ReplaceWithCAArn
      Tags:
        Environment: Test
        Owner: QATeam
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        InstanceType: kafka.t3.small
#        SecurityGroups:
#          - ReplaceWithSecurityGroupId
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: !Ref VolumeSize
        ClientSubnets: !Ref Subnets