apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: go-app
  name: go-app
spec:
  ports:
    - port: {{ .Values.application.service.port }}
      protocol: TCP
      targetPort: {{ .Values.application.port }}
  selector:
    app: go-app
status:
  loadBalancer: {}
