apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app
    spec:
      containers:
      - image: {{ .Values.aws.accountid }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com/node-app:{{ .Values.imageTag }}
        name: node-app
        ports:
        - containerPort: {{ .Values.application.port }}
        env:
        - name: CLIENT_ID
          value: "node-app"
        - name: TOPIC
          value: {{ .Values.kafka.topic }}
        - name: BROKERS
          value: {{ .Values.kafka.broker }}
