apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-app
  name: node-app
spec:
  ports:
    - port: {{ .Values.application.service.port }}
      protocol: TCP
      targetPort: {{ .Values.application.port }}
  selector:
    app: node-app
status:
  loadBalancer: {}
